# Exploratory Data Analysis Project
TODO: Write summary

## Dataset Information
TODO:

# Project Setup
TODO: Share info about tools used

In [ ]:
import logging  # for type hinting only
from typing import Final  # for type hinting

from datafun_toolkit.logger import get_logger, log_header
import pandas as pd
import seaborn as sns

# A figure can contain multiple axes (plots)
# from matplotlib.figure import Figure

# === Section 1b. CONFIGURE LOGGER ONCE PER NOTEBOOK ===

LOG: logging.Logger = get_logger("EDA-NBA", level="DEBUG")
log_header(LOG, "EDA-NBA")

# CUSTOM: Data set name
# Available seaborn datasets: ['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones',
#'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

LOG.info("Choosing Dataset")
DATASET_NAME: Final[str] = "tips"  # CUSTOM: Change this to your desired dataset

LOG.info("Quickly Summarize Dataset To Confirm Suitability")

LOG.info(f"Loading dataset: {DATASET_NAME}")
df: pd.DataFrame = sns.load_dataset(DATASET_NAME)

LOG.info(f"Loaded: {df.shape[0]} rows, {df.shape[1]} columns")

LOG.info("Previewing first few rows of the dataset")
display(df.head())

LOG.info("Column names")
print(list(df.columns))

display(df.describe())

# CUSTOM: Grouping column (chose one categorical/non-numeric variable)
# GROUP_COL: Final[str] = "species"

# CUSTOM: Numeric columns to analyze (chose 4-5 numeric variables)
"""SELECTED_NUMERIC_COLS: Final[list[str]] = [
    "bill_length_mm",
    "bill_depth_mm",
    "flipper_length_mm",
    "body_mass_g",
]
"""
# === Section 1d. Pandas Configuration for Display ===

# Pandas display configuration (helps in notebooks)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

LOG.info("Imports complete.")

2026-06-04 11:41:07 | INFO | EDA-NBA | === RUN START ===
2026-06-04 11:41:07 | INFO | EDA-NBA | project=EDA-NBA
2026-06-04 11:41:07 | INFO | EDA-NBA | repo_dir=datafun-04-notebooks
2026-06-04 11:41:07 | INFO | EDA-NBA | python=3.14.0
2026-06-04 11:41:07 | INFO | EDA-NBA | os=Windows 11
2026-06-04 11:41:07 | INFO | EDA-NBA | shell=powershell
2026-06-04 11:41:07 | INFO | EDA-NBA | cwd=notebooks
2026-06-04 11:41:07 | INFO | EDA-NBA | github_actions=False
2026-06-04 11:41:07 | INFO | EDA-NBA | Choosing Dataset
2026-06-04 11:41:07 | INFO | EDA-NBA | Quickly Summarize Dataset To Confirm Suitability
2026-06-04 11:41:07 | INFO | EDA-NBA | Loading dataset: tips
2026-06-04 11:41:07 | INFO | EDA-NBA | Loaded: 244 rows, 7 columns
2026-06-04 11:41:07 | INFO | EDA-NBA | Previewing first few rows of the dataset

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

2026-06-04 11:41:07 | INFO | EDA-NBA | Column names

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

2026-06-04 11:41:07 | INFO | EDA-NBA | Imports complete.